### ISSUE TITLE
Not working with version 16 of Relay

### ISSUE THREAD

**Issue by luizpcf** [iamchanii/storybook-addon-relay#3]
Dependency is set to Relay 14, so I get this error when trying to install the addon:

<img width="1037" alt="Screenshot 2023-12-20 at 10 15 26 PM" src="https://github.com/iamchanii/storybook-addon-relay/assets/1350150/b7e0badc-c12f-4af6-9fd2-e8be14ce195b">

**Comment by iamchanii** [comment]
Sorry for late respond. I just published 0.0.10 to update peer deps which related with Relay. Try install latest version and let me notice if it is not working.
