### ISSUE TITLE
Support for useQueryLoader / usePreloadedQuery

### ISSUE THREAD

**Issue by advl** [iamchanii/storybook-addon-relay#4]
Hi,

This library has been very useful for me for the past months and am using it for a lot of my components, I find it very well designed and with a clean api.

What do you think of testing components using useQueryLoader/usePreloadedQuery - do you imagine it would be a good idea to find a way to also mock graphql requests for those ?

Thanks for the great work !

**Comment by iamchanii** [comment]
I don't have been write test cases with usePreloadedQuery so this library is focused on very specific cases which components uses `useFragment` hooks. If I read Relay docs correctly, `usePreloadedQuery` will be testable also.
